### ISSUE TITLE
Server side light grid does not get data correctly

### ISSUE THREAD

**Issue by Wojtasik** [michaldudak/light-grid#1]
When using light grid with server side provider it does not get data correctly. It fetches them, but returns empty array. Probably it's because `sendRequest` method uses `$http.success` instead of `$http.then`.

**Comment by Wojtasik** [comment]
Nevermind. It's working well. The data property mislead me. You can close it.

**Comment by TheOneYouDontLike** [comment]
Ok, I've read the lg docs and it seems that this issue is invalid.
Data provider expects object with `data` property in it.

**Comment by michaldudak** [comment]
Sorry for the late reply. Yes, by default it expects the 'data' property, but you may override it by providing a custom responseParser
