### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by armandchard** [michaldudak/light-grid#7]
Hello,
Can you make a bower package of your component? 
I think it's more easier to use at end.

Regards,
Armand.

**Comment by michaldudak** [comment]
Sure, I'll look into it.

**Comment by armandchard** [comment]
Thank you, tell me when it's ready, I'm impatient :)

**Comment by michaldudak** [comment]
Done, Light Grid is now available in Bower registry.

**Comment by armandchard** [comment]
Thanks a lot! I'll install it right now
