### ISSUE TITLE
Plunker examples request

### ISSUE THREAD

**Issue by lacivert** [michaldudak/light-grid#9]
Can you please put some plunker examples? I think it would be very much useful for new comers to see this. And I couldn't make it work either because you made the website demo with a special js file which is minified and not known what are dependencies are required.

**Comment by michaldudak** [comment]
Hi, sorry for the late response, I must have missed the notification. I'll try to update the docs in the upcoming days.

**Comment by michaldudak** [comment]
I've created the fully-featured grid sample on Plunkr: https://plnkr.co/edit/M4XD6nefVuLX2bjXZqA7?p=preview

**Comment by lacivert** [comment]
Thank you very much
